name: Update README with Uptime

on:
  schedule:
    - cron: "0 3 * * *" # once a day
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Calculate uptime
        run: |
          YEARS=$(( $(date +%Y) - 2006 ))
          MONTHS=$(( $(date +%m) - 8 ))
          sed -i "s/Uptime: ................. .*/Uptime: ................. ${YEARS} years, ${MONTHS} months/" README.md

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "ðŸŒ€ Auto-update uptime"
          git push
